spring.application.name=lootsafe-v2
spring.config.import=optional:file:.env[.properties]
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.default-property-inclusion=non_null

spring.jpa.show-sql=false
spring.flyway.enabled=true

jwt.secret=${JWT_SECRET}
jwt.expirationMs=${JWT_EXPIRATION_MS}
jwt.refreshExpirationMs=${JWT_REFRESH_EXPIRATION_MS}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

encryption.password=${ENCRYPTION_PASSWORD}
encryption.salt=${ENCRYPTION_SALT}

mercadopago.access-token=${MERCADOPAGO_ACCESS_TOKEN}
mercadopago.webhook-secret=${MERCADOPAGO_WEBHOOK_SECRET}

payment.pix-validity-hours=${PAYMENT_PIX_VALIDITY_HOURS}
payment.expiration-check-interval-ms=${PAYMENT_EXPIRATION_CHECK_INTERVAL_MS}