spring.application.name=lootsafe-v2
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.default-property-inclusion=non_null

spring.jpa.show-sql=true
spring.flyway.enabled=true

jwt.secret=dev-jwt-secret-key-with-at-least-32-bytes!!
jwt.expirationMs=900000
jwt.refreshExpirationMs=604800000

spring.datasource.url=jdbc:postgresql://localhost:5435/escrow_dev
spring.datasource.username=escrow
spring.datasource.password=escrow
spring.datasource.driver-class-name=org.postgresql.Driver

encryption.password=dev-password
encryption.salt=deadbeefdeadbeef


mercadopago.access-token=${MERCADOPAGO_ACCESS_TOKEN:TEST-token-temporario-dev}
mercadopago.webhook-secret=${MERCADOPAGO_WEBHOOK_SECRET:secret-temporario-dev}

